language: node_js
node_js:
    - lts/*
before_install:
    - export TZ='Asia/Shanghai'  # 设置时区    
install:
    - yarn install
script:
    - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  local-dir: ./public/ ## 根据情况自定义到静态文件输出目录
  target-branch: main
  keep_history: true
  on:
    branch: master
